### ISSUE TITLE
Get a typescript file by each CSS

### ISSUE THREAD

**Issue by ezavile** [ezavile/postcss-typescript-css#4]
Given a CSS file the plugin has to create a typescript file.
### componentName.postcss
```css
.ComponentName {
   color: red;
}
.ComponentName-descendentName {
   color: yellow;
}
.ComponentName--modifierName {
   color: green;
}
```
### componentName.ts
```typescript
export const componentNameStyle = {
   componentName: 'ComponentName',
   componentDescendentName: 'ComponentName-descendentName',
   componentModifierName: 'ComponentName--modifierName',
}
```
## Usage
```typescript
import './componentName.postcss';
import { componentNameStyle } from './componentName';

import { helloWorldStyle, otherComponentStyle } from './style';
const element = document.createElement('div');
element.className = componentNameStyle.componentName;
